### ISSUE TITLE
Look at the Prodapt title.

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#42]
This is a different type of long term program. 

Please make a Digest for for this type of Programs. 

[Prodapt Impactful Innovation Phase 2 V 3.3 plain.pdf](https://github.com/kumarana/Data-Analytics/files/3465654/Prodapt.Impactful.Innovation.Phase.2.V.3.3.plain.pdf)

**Comment by aparnaraon** [comment]
[tiny peek parameters- DOJO.xlsx](https://github.com/kumarana/Data-Analytics/files/3485673/tiny.peek.parameters-.DOJO.xlsx)
This is just a starting point- pre draft. I have the foll questions-
1. Do we need to measure individual performers or is this a group performance indicator? I have included individual  too since we can add it up to team performance

**Comment by kumarana** [comment]
[Innovation Index V6.0.xlsx](https://github.com/kumarana/Data-Analytics/files/3528512/Innovation.Index.V6.0.xlsx)

The innovation index

**Comment by aparnaraon** [comment]
Added a few more  features .
[tiny peek parameters- DOJO.xlsx](https://github.com/kumarana/Data-Analytics/files/3578720/tiny.peek.parameters-.DOJO.xlsx)
