### ISSUE TITLE
Magiq spark Level 2 excercises

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#8]
Level 2 queries 
1. Average number of mentees checked-in  / day for each chain for a group from the Group start date for 2 months. ( Pick any group older than 6 months ) . 
For e.g 
 Chain 1 , 6 mentees 
 Chain 2,  5 mentees
2. Get the list of users who have missed check-ins.

**Comment by aparnaraon** [comment]
> Level 2 queries
> 
> 1. Average number of mentees checked-in  / day for each chain for a group from the Group start date for 2 months. ( Pick any group older than 6 months ) .
>    For e.g
>    Chain 1 , 6 mentees
>    Chain 2,  5 mentees
•	1st step is to find a group , > 6 months= “ SELECT * FROM Latestmagiqspark.Groups WHERE program_start_date < = “ 2018-09-30” ; 61 rows were returned. Group chosen- Mphasis digital architect group. Group id = 36
•	Get a complete list of chains for this group- SELECT  * FROM chains  WHERE  group_id = ‘36’. 14 chains were returned.
•	Select chain – ILI chain_id = 101, CQA@work chain_id = 110 , relate pillars challenge chain_id = 153 [ why I chose these 3 chains is because they are to be checked in daily]
•	Select period = 2 months from start date
•	Get the AVG no of mentees checked in for this chain
•	Repeat the previous 3 steps for the remaining chains

> 2. Get the list of users who have missed check-ins.

**Comment by aparnaraon** [comment]
•	1st step is to find a group , > 6 months= “ SELECT * FROM Latestmagiqspark.Groups WHERE program_start_date < = “ 2018-09-30” ; 61 rows were returned. Group chosen- Mphasis digital architect group. Group id = 36
•	Get a complete list of chains for this group- SELECT  * FROM chains  WHERE  group_id = ‘36’. 14 chains were returned.
•	Select chain – ILI chain_id = 101, CQA@work chain_id = 110 , relate pillars challenge chain_id = 153 [ why I chose these 3 chains is because they are to be checked in daily]
•	Select period = 2 months from start date
•	Get the AVG no of mentees checked in for this chain
•	Repeat the previous 3 steps for the remaining chains
Please check if the above is right. Unable to proceed. Last 2 steps, I havent been able to do.

**Comment by kumarana** [comment]
This has to be a single query not multiple queries
